# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 24 Feb 2020 21:45:11 +0000
*	@ALL	1
*	@user	1
*	@editor	8
cs:poselstvi_gralu:1949-1950:*	@ALL	0
cs:poselstvi_gralu:1949-1950:*	@user	1
cs:prednasky:nevydane:*	@user	1
cs:prednasky:nevydane:*	@ALL	0
cs:prednasky:nezarazene_hlas:*	@ALL	0
cs:prednasky:nezarazene_hlas:*	@user	1
de:gralsbotschaft:1941:*	@ALL	0
de:gralsbotschaft:1941:*	@user	1
de:gralsbotschaft:1949-1950:*	@user	1
de:gralsbotschaft:1949-1950:*	@ALL	0
de:vortrage:unveroffentlichte:*	@ALL	0
de:vortrage:unveroffentlichte:*	@user	1
de:vortrage:unveroffentlichte:gebet_1929	@ALL	1
de:vortrage:unveroffentlichte:lichtgebet_1937	@ALL	1
de:vortrage:veroffentlichte:1936-1937:*	@ALL	0
de:vortrage:veroffentlichte:1936-1937:*	@user	1
de:vortrage:veroffentlichte:vertrauliche:*	@ALL	0
de:vortrage:veroffentlichte:vertrauliche:*	@user	1
epub:*	@ALL	0
epub:*	@admin	8
sidebar	@ALL	1
sidebar	@admin	2
wiki:*	@admin	16
wiki:*	@ALL	0
cs:poselstvi_gralu:1984-1986:*	@user	1
cs:poselstvi_gralu:1984-1986:*	@ALL	0
de:gralsbotschaft:1984-1986:*	@ALL	0
de:gralsbotschaft:1984-1986:*	@user	1
cs:doznivani:1934:plamen:*	@editor	1
cs:prednasky:nezarazene_plamen:*	@ALL	0
cs:prednasky:nezarazene_plamen:*	@user	1
cs:prednasky:nezarazene_plamen:drive_nez_byl_abraham_jsem_ja	@ALL	1
cs:prednasky:nezarazene_plamen:lidske_smysleni_a_bozi_vule_v_zakone_vzajemneho_pusobeni	@ALL	1
cs:prednasky:nezarazene_plamen:volani	@ALL	1
cs:prednasky:nezarazene_plamen:tajemstvi_krve	@ALL	1
cs:prednasky:nezarazene_plamen:rec_pane	@ALL	1
cs:prednasky:nezarazene_plamen:detskost	@ALL	1
cs:prednasky:nezarazene_plamen:clovek_a_zeme	@ALL	1
cs:prednasky:nezarazene_plamen:letnice	@ALL	1
cs:prednasky:nezarazene_plamen:prvni_krok	@ALL	1
cs:prednasky:nezarazene_plamen:cudnost	@ALL	1
cs:prednasky:nezarazene_plamen:zachrana_spasa	@ALL	1
cs:prednasky:nezarazene_plamen:kult	@ALL	1
cs:prednasky:nezarazene_plamen:strnulost	@ALL	1
epub:*	@user	1
wiki:*	@user	1
