<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: rolfik
 * Date: Fri, 18 Feb 2022 11:53:08 +0100
 */

$conf['title'] = 'Abd-ru-shin';
$conf['tagline'] = 'Abdruschin - Abdrushin - Oskar Ernst Bernhardt';
$conf['license'] = '0';
$conf['basedir'] = '/';
$conf['allowdebug'] = 1;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['tocminheads'] = '0';
$conf['maxtoclevel'] = '0';
$conf['maxseclevel'] = '0';
$conf['useheading'] = '1';
$conf['hidepages'] = '^:(sidebar|playground|wiki|epub)';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'index';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['subscribers'] = 1;
$conf['notify'] = 'marek.istvanek@abdrushin.one';
$conf['registernotify'] = 'marek.istvanek@abdrushin.one';
$conf['mailfrom'] = 'info@abdrushin.one';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['canonical'] = 1;
$conf['search_fragment'] = 'contains';
$conf['plugin']['addnewpage']['addpage_exclude'] = 'playground';
$conf['plugin']['addnewpage']['addpage_showroot'] = 0;
$conf['plugin']['addnewpage']['addpage_hideACL'] = 1;
$conf['plugin']['multilingual']['enabled_langs'] = 'de en cs sk';
$conf['plugin']['dw2pdf']['pagesize'] = 'A5';
$conf['plugin']['dw2pdf']['toclevels'] = '1-1';
$conf['plugin']['dw2pdf']['template'] = 'book';
$conf['plugin']['dw2pdf']['output'] = 'browser';
$conf['plugin']['dw2pdf']['usestyles'] = 'wrap,noprint,pagebreak';
$conf['plugin']['dw2pdf']['qrcodesize'] = '';
$conf['plugin']['translation']['translations'] = 'de en cs sk';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['translation']['checkage'] = 1;
$conf['plugin']['translation']['localabout'] = 1;
$conf['plugin']['translation']['copytrans'] = 1;
$conf['plugin']['navigation']['pageMenuLevelItems'] = 'Bottom,First,Previous,Outside,Inside,Next,Last';
$conf['plugin']['bookcreator']['skip_ids'] = 'sidebar,user,group,playground,wiki:syntax,wiki:ebook,:epub:';
$conf['plugin']['pagelist']['showuser'] = '0';
$conf['plugin']['toctweak']['maxtoclevel'] = '0';
$conf['plugin']['toctweak']['tocminheads'] = '0';
$conf['plugin']['headerfooter']['separation'] = 'nothing';
$conf['plugin']['indexmenu']['defaultoptions'] = 'msort nsort';
$conf['plugin']['indexmenu']['headpage'] = ':start:';
$conf['plugin']['indexmenu']['skip_index'] = '/(playground)/';
$conf['plugin']['catlist']['nocache'] = '1';
$conf['plugin']['tag']['toolbar_icon'] = '1';

// end auto-generated content